# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-17 16:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KeyWordsInfo',
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
