# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-16 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=30)),
                ('mail', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('add_time', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
