# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-16 13:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20180316_2103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keywordsinfo',
            old_name='keyword_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='user_mail',
            new_name='mail',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='user_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='user_password',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='keywordsinfo',
            name='keyword_create_time',
        ),
        migrations.RemoveField(
            model_name='keywordsinfo',
            name='keyword_id',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='user_create_time',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='user_id',
        ),
        migrations.AddField(
            model_name='keywordsinfo',
            name='create_time',
            field=models.DateField(auto_now_add=True, default='2018.3.16', verbose_name='create time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='create_time',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='create time'),
            preserve_default=False,
        ),
    ]
