# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-16 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20180316_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywordsinfo',
            name='create_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='create_time',
            field=models.DateField(),
        ),
    ]
