# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-19 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
        migrations.AddField(
            model_name='profile',
            name='favor_id',
            field=models.CharField(default='', max_length=50),
        ),
    ]
