# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-19 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20180419_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='', max_length=50)),
                ('document_id', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
