# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-21 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20180321_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='Dshoulu_date',
            field=models.CharField(max_length=50),
        ),
    ]
