# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-21 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20180321_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='Dauther',
            field=models.CharField(max_length=150),
        ),
    ]
