# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-21 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20180321_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='Dkeyword',
            field=models.CharField(default='\u764c\u75c7', max_length=50),
            preserve_default=False,
        ),
    ]
